export const skills = [
  { text: `Technical strategy` },
  { text: `Architecture` },
  { text: `TypeScript` },
  { text: `Node.js` },
  { text: `Python` },
  { text: `React` },
  { text: `Next.js` },
  { text: `Angular` },
  { text: `WCAG 2.1 Accessibility` },
  { text: `Design Systems expert` },
  { text: `CSS` },
  { text: `SCSS` },
  { text: `Tailwind` },
  { text: `PostgreSQL` },
  { text: `MongoDB` },
  { text: `Redis` },
  { text: `ElasticSearch` },
  { text: `Docker` },
  { text: `k8s` },
  { text: `Rest` },
  { text: `GraphQL` },
  { text: `Observability` },
  { text: `Git` },
  { text: `Github` },
  { text: `Continuous Integration` },
  { text: `Continuous Deployments` },
  { text: `Webpack & Vite` },
  { text: `Cypress` },
  { text: `Nightwatch` },
  { text: `TDD` },
  { text: `Advanced Testing` },
  { text: `Jira` },
  { text: `Cross-functional team leadership` },
  { text: `Agile: Scrum & Kanban` },
  { text: `Mentoring` },
]
