export const skills = [
  { text: `Technical strategy` },
  { text: `Architecture` },
  { text: `TypeScript` },
  { text: `Node.js` },
  { text: `Python` },
  { text: `React` },
  { text: `Next.js` },
  { text: `Redux` },
  { text: `Angular` },
  { text: `WCAG 2.1 Accessibility` },
  { text: `Design Systems expert` },
  { text: `CSS` },
  { text: `SCSS` },
  { text: `Tailwind` },
  { text: `PostgreSQL` },
  { text: `MongoDB` },
  { text: `Redis` },
  { text: `ElasticSearch` },
  { text: `Docker` },
  { text: `k8s` },
  { text: `Rest` },
  { text: `Microservices` },
  { text: `GraphQL` },
  { text: `Observability` },
  { text: `Bash` },
  { text: `Git` },
  { text: `Github` },
  { text: `Continuous Integration` },
  { text: `Continuous Deployments` },
  { text: `Webpack` },
  { text: `Vite` },
  { text: `Monorepos` },
  { text: `Micro-frontends` },
  { text: `Cypress` },
  { text: `Playwright` },
  { text: `TDD` },
  { text: `Extreme Programming` },
  { text: `Advanced Testing` },
  { text: `Jira` },
  { text: `Cross-functional team leadership` },
  { text: `Scrum & Kanban` },
  { text: `Mentoring` },
  { text: `Documentation` },
]
